### ISSUE TITLE
doc: Outdated descriptions

### ISSUE THREAD

**Issue by 4513ECHO** [Shougo/dpp-ext-toml#3]
I've found some outdated descriptions in `doc/dpp-ext-toml.txt`:

1. `MultipleHook` is now exported from [`jsr:@shougo/dpp-vim`](https://jsr.io/@shougo/dpp-vim), users does not have to define it manually.

https://github.com/Shougo/dpp-ext-toml/blob/e854e37a2122f897e6dbb973ec1b2e85b9acd0ca/doc/dpp-ext-toml.txt#L36-L41

2. "load" action never returns `undefined`.

https://github.com/Shougo/dpp-ext-toml/blob/e854e37a2122f897e6dbb973ec1b2e85b9acd0ca/doc/dpp-ext-toml.txt#L63

3. dpp-ext-toml does not have "local" action.

https://github.com/Shougo/dpp-ext-toml/blob/e854e37a2122f897e6dbb973ec1b2e85b9acd0ca/doc/dpp-ext-toml.txt#L79

4. The `ftplugin` attribute in toml has been renamed to `ftplugins`.

https://github.com/Shougo/dpp-ext-toml/blob/e854e37a2122f897e6dbb973ec1b2e85b9acd0ca/doc/dpp-ext-toml.txt#L107-L108

**Comment by Shougo** [comment]
> "load" action never returns undefined.

It means `extAction` may return `undefined` if the ext is not installed.  So it is not issue.

I have fixed other issues.
